matrix:
  include:
    - language: c
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - valgrind
      before_script:
        - cd ./Release/
      script:
        - make test
    - language: c
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - splint
      before_script:
        - sudo apt-get install -y libpcre2-dev libuv1-dev uuid-dev
        - git clone https://github.com/transceptor-technology/libcleri.git
        - cd ./libcleri/Release/
        - make
        - sudo make install
        - cd ../../
      script:
        - splint *.c

